### ISSUE TITLE
Solus 3.9/4.20.10-111.current

### ISSUE THREAD

**Issue by lukejackson958** [JussiVJ/vfio-conf#3]
> luke@thanos ~/Downloads/vfio-conf-release $ sudo python3 gui.py
> Passwort:
> ls: Zugriff auf '/etc/modprobe.d/' nicht möglich: Datei oder Verzeichnis nicht gefunden
> Traceback (most recent call last):
>   File "gui.py", line 7, in <module>
>     files = str(subprocess.check_output(['ls', '/etc/modprobe.d/']))
>   File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 438, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ls', '/etc/modprobe.d/']' returned non-zero exit status 2.

> lspci -nn
> 
> 00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers [8086:191f] (rev 07)
> 
> 00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 07)
> 
> 00:02.0 Display controller [0380]: Intel Corporation HD Graphics 530 [8086:1912] (rev 06)
> 
> 00:14.0 USB controller [0c03]: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller [8086:a12f] (rev 31)
> 
> 00:16.0 Communication controller [0780]: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 [8086:a13a] (rev 31)
> 
> 00:17.0 SATA controller [0106]: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] [8086:a102] (rev 31)
> 
> 00:1b.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #17 [8086:a167] (rev f1)
> 
> 00:1b.2 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #19 [8086:a169] (rev f1)
> 
> 00:1b.3 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #20 [8086:a16a] (rev f1)
> 
> 00:1c.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #1 [8086:a110] (rev f1)
> 
> 00:1c.2 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #3 [8086:a112] (rev f1)
> 
> 00:1c.3 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #4 [8086:a113] (rev f1)
> 
> 00:1c.4 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #5 [8086:a114] (rev f1)
> 
> 00:1d.0 PCI bridge [0604]: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #9 [8086:a118] (rev f1)
> 
> 00:1f.0 ISA bridge [0601]: Intel Corporation Z170 Chipset LPC/eSPI Controller [8086:a145] (rev 31)
> 
> 00:1f.2 Memory controller [0580]: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller [8086:a121] (rev 31)
> 
> 00:1f.3 Audio device [0403]: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller [8086:a170] (rev 31)
> 
> 00:1f.4 SMBus [0c05]: Intel Corporation 100 Series/C230 Series Chipset Family SMBus [8086:a123] (rev 31)
> 
> 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070] [10de:1b81] (rev a1)
> 
> 01:00.1 Audio device [0403]: NVIDIA Corporation GP104 High Definition Audio Controller [10de:10f0] (rev a1)
> 
> 03:00.0 Ethernet controller [0200]: Qualcomm Atheros Killer E2400 Gigabit Ethernet Controller [1969:e0a1] (rev 10)
> 
> 05:00.0 USB controller [0c03]: ASMedia Technology Inc. ASM1142 USB 3.1 Host Controller [1b21:1242]
> 
> 09:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981 [144d:a808]

**Comment by lukejackson958** [comment]
hello,
first time submitting an issue, hope i added all the relevant info.
i searched for /modprobe.d/ on my system and i could only find "/usr/lib64/modprobe.d"
i tried to replace /etc/modprobe.d with usr/lib64/modprobe.d but i still get missing files errors:

>  luke@thanos ~/Downloads/vfio-conf-release $ sudo python3 gui.py
> cp: reguläre Datei '/etc/modprobe.d/vfioconf.conf' kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
> Traceback (most recent call last):
>   File "gui.py", line 17, in <module>
>     for line in fileinput.FileInput("/usr/lib64/modprobe.d/vfioconf.conf", inplace=1):
>   File "/usr/lib/python3.6/fileinput.py", line 250, in __next__
>     line = self._readline()
>   File "/usr/lib/python3.6/fileinput.py", line 337, in _readline
>     os.rename(self._filename, self._backupfilename)
> FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/usr/lib64/modprobe.d/vfioconf.conf' -> '/usr/lib64/modprobe.d/vfioconf.conf.bak'

**Comment by lukejackson958** [comment]
Im on Solus 4.0 now and im getting a different error:
`luke@thanos ~/Downloads/vfio-conf-release $ sudo python3 gui.py

  File "gui.py", line 13
    subprocess.call(["cp", "resources/vfioconf_modprobe.conf", "/etc/modprobe.d/vfioconf.conf
                                                                                            ^
SyntaxError: EOL while scanning string literal
`

**Comment by JussiVJ** [comment]
Hi and sorry for taking so long to respond, Solus is not currently supported, but that doesn't necessarily mean the ´program won't work. Please give me the output of "ls /etc/modprobe.d/". Also is /etc/modprobe.d a symlink to /usr/lib64/modprobe.d?

**Comment by lukejackson958** [comment]
no worries, appreciating the effort. 

`ls /etc/modprobe.d/
ls: Zugriff auf '/etc/modprobe.d/' nicht möglich: Datei oder Verzeichnis nicht gefunden`

i ran

`luke@thanos /usr/lib64/modprobe.d $ find . -maxdepth 1 -type l -ls`

and got no output, is that what you asked? quite a noob here

**Comment by JussiVJ** [comment]
Thanks, that's exactly what I asked for, but as the /etc/modprobe.d dir doesn't seem to exist on solus so the program won't work on solus. I might implement support for solus at some point.
