### ISSUE TITLE
Problems occur with large numbers of items listed

### ISSUE THREAD

**Issue by NotSoren** [JussiVJ/vfio-conf#5]
![as we can see, I can't read half of the items here. It's mildly problematic.](https://user-images.githubusercontent.com/49254922/59174880-0e741a80-8b08-11e9-848b-bdd8c447c7bc.png)

This page goes off my screen and really could do with being resizable. Just a suggestion.

**Comment by JussiVJ** [comment]
I have added filtering to the pci devices shown, but that doesn't happen to help you as it looks for specific keywords. As soon as I get back home ill update the menu and see if I can make the menu scrollable.

**Comment by NotSoren** [comment]
Very nice. Thanks for the quick response!
